In [1]:
import numpy as np

In [7]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
a=np.array(([1,2,3],[3,4,5],[5,6,7]))
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [23]:
a=np.array([1,2,3,4,5])
np.flipud(a)

array([5, 4, 3, 2, 1])

In [27]:
a=np.arange(1,10)
print(a)
b=np.sum(a)
print(b)

np.mean(a)

np.std(a)

[1 2 3 4 5 6 7 8 9]
45


2.581988897471611

In [36]:
a=(np.random.randint(1,100,(5,5)))
print(a)
print(np.max(a))
print(np.min(a))


[[69  3 83 50 79]
 [42 39 25 22 93]
 [40 45 73 29 46]
 [70 35 98 82 56]
 [99 99 65 75 84]]
99
3


In [53]:
a=np.arange(1,50,9)
print(a)
b=a.reshape(2,3)
print(b)
c=b[b%2==1]
print(c)

[ 1 10 19 28 37 46]
[[ 1 10 19]
 [28 37 46]]
[ 1 19 37]


In [37]:
a=np.random.randint(1,50,(3,3))
b=np.random.randint(51,100,(3,3))
print(a)
print(b)

[[41 23 24]
 [46 42 15]
 [17 42 29]]
[[55 72 96]
 [74 94 78]
 [55 73 97]]


In [38]:
print(a*b)

[[2255 1656 2304]
 [3404 3948 1170]
 [ 935 3066 2813]]


In [41]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.unique(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [54]:
a=np.arange(1,50,9)
print(a)
b=a.reshape(2,3)
print(b)
c=b[b%2==0]
print(c)

[ 1 10 19 28 37 46]
[[ 1 10 19]
 [28 37 46]]
[10 28 46]


In [58]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

odd= array[:, 1::2]
print(odd)



[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [61]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

even= array[:, 0::2]
print(even)



[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]


In [62]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])
np.flipud(array)

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])