In [2]:
import numpy as np

In [3]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
a=np.array(([1,2,3],[3,4,5],[5,6,7]))
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [6]:
a=np.array([1,2,3,4,5])
np.flipud(a)

array([5, 4, 3, 2, 1])

In [7]:
a=np.arange(1,10)
print(a)
b=np.sum(a)
print(b)

np.mean(a)

np.std(a)

[1 2 3 4 5 6 7 8 9]
45


2.581988897471611

In [8]:
a=(np.random.randint(1,100,(5,5)))
print(a)
print(np.max(a))
print(np.min(a))


[[65 74  9 95 57]
 [68 16 73 27 84]
 [69 10 30 56 39]
 [ 2  7 22 73 44]
 [55 33 95 23 81]]
95
2


In [9]:
a=np.arange(1,50,9)
print(a)
b=a.reshape(2,3)
print(b)
c=b[b%2==1]
print(c)

[ 1 10 19 28 37 46]
[[ 1 10 19]
 [28 37 46]]
[ 1 19 37]


In [10]:
a=np.random.randint(1,50,(3,3))
b=np.random.randint(51,100,(3,3))
print(a)
print(b)

[[39 26  9]
 [ 6 30 16]
 [20 19 36]]
[[99 64 98]
 [71 94 82]
 [72 68 91]]


In [11]:
print(a*b)

[[3861 1664  882]
 [ 426 2820 1312]
 [1440 1292 3276]]


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.unique(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [13]:
a=np.arange(1,50,9)
print(a)
b=a.reshape(2,3)
print(b)
c=b[b%2==0]
print(c)

[ 1 10 19 28 37 46]
[[ 1 10 19]
 [28 37 46]]
[10 28 46]


In [14]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

odd= array[:, 1::2]
print(odd)



[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [15]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])

even= array[:, 0::2]
print(even)



[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]


In [16]:
array = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])
np.flipud(array)

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [17]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])