importing

In [13]:
import numpy as np

In [14]:
#set precision
np.set_printoptions(precision=2)

creating matrix

In [15]:
a=np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [16]:
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [17]:
c=np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


.generate matrix
  -linear
  -random

In [18]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
a=np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [20]:
b=np.linspace(1,10,100)
print(b)
b.size

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


100

In [21]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [22]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [24]:
np.random.rand(3,3)

array([[0.54, 0.73, 0.19],
       [0.61, 0.64, 0.31],
       [0.45, 0.96, 0.54]])

In [25]:
np.random.randn(3,3)

array([[-0.61,  1.21, -0.54],
       [-0.7 ,  0.54,  0.05],
       [ 0.31,  0.07, -0.07]])

In [26]:
print(np.random.randint(1,100,(5,3)))

[[23  9 41]
 [27 34 62]
 [29 45 53]
 [ 1 47 82]
 [99 39 72]]


In [27]:
x=np.random.randint(1,11,(3,3))
y=np.random.randint(1,11,(3,3))
print(x)
print(y)

[[ 5 10  5]
 [ 9  1  1]
 [ 7  5  6]]
[[ 3  4  8]
 [10 10 10]
 [ 3  6  9]]


In [28]:
x+y

array([[ 8, 14, 13],
       [19, 11, 11],
       [10, 11, 15]])

In [29]:
x -y

array([[ 2,  6, -3],
       [-1, -9, -9],
       [ 4, -1, -3]])