importing

In [1]:
import numpy as np

In [2]:
#set precision
np.set_printoptions(precision=2)

creating matrix

In [3]:
a=np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [4]:
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [5]:
c=np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


.generate matrix
  -linear
  -random

In [6]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [7]:
a=np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [8]:
b=np.linspace(1,10,100)
print(b)
b.size

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


100

In [9]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [10]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [11]:
np.random.rand(3,3)

array([[0.41, 0.83, 0.16],
       [0.81, 0.9 , 0.74],
       [0.64, 0.99, 0.57]])

In [12]:
np.random.randn(3,3)

array([[-1.65,  0.16,  0.35],
       [-1.47,  0.21,  1.46],
       [-0.26,  0.41,  0.57]])

In [13]:
print(np.random.randint(1,100,(5,3)))

[[72  1 56]
 [68 29 22]
 [50 75 18]
 [61 60 56]
 [24 41 30]]


In [14]:
x=np.random.randint(1,11,(3,3))
y=np.random.randint(1,11,(3,3))
print(x)
print(y)

[[ 7  2  7]
 [10  1  4]
 [ 2  5 10]]
[[10  6 10]
 [ 9  1  2]
 [ 2  5  9]]


In [15]:
x+y

array([[17,  8, 17],
       [19,  2,  6],
       [ 4, 10, 19]])

In [16]:
x -y

array([[-3, -4, -3],
       [ 1,  0,  2],
       [ 0,  0,  1]])

21 aug

In [17]:
x=np.random.randint(20,50,(6,6))
print(x)

[[47 46 44 44 38 20]
 [49 30 41 49 43 46]
 [35 40 38 36 30 38]
 [30 39 27 21 22 39]
 [45 25 45 48 39 41]
 [35 20 21 46 20 24]]


In [19]:
z=[]
for i in x:
    for j in i:
        if j > 30:
            z.append(j)
print(np.array(z)) 
#this is not the best way           



[47 46 44 44 38 49 41 49 43 46 35 40 38 36 38 39 39 45 45 48 39 41 35 46]


easy way

In [20]:
x>30#filter

array([[ True,  True,  True,  True,  True, False],
       [ True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [False,  True, False, False, False,  True],
       [ True, False,  True,  True,  True,  True],
       [ True, False, False,  True, False, False]])

In [21]:
x[x>30]#boolean filter

array([47, 46, 44, 44, 38, 49, 41, 49, 43, 46, 35, 40, 38, 36, 38, 39, 39,
       45, 45, 48, 39, 41, 35, 46])

In [22]:
f=x<40
x[f]

array([38, 20, 30, 35, 38, 36, 30, 38, 30, 39, 27, 21, 22, 39, 25, 39, 35,
       20, 21, 20, 24])

In [23]:
x[(x>30)&(x<45)]

array([44, 44, 38, 41, 43, 35, 40, 38, 36, 38, 39, 39, 39, 41, 35])

slicing
1D=[start : stop : step]
2D=[r_start : r_stop : r_step : , c_start : c_stop : c_step]

In [24]:
print('first row')
print(x[1])

first row
[49 30 41 49 43 46]


In [25]:
print('last row')
print(x[-1])

last row
[35 20 21 46 20 24]


In [26]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[35 40 38 36 30 38]
 [30 39 27 21 22 39]
 [45 25 45 48 39 41]
 [35 20 21 46 20 24]]


In [27]:
x[:,3]

array([44, 49, 36, 21, 48, 46])

In [30]:
x[:,-3:]

array([[44, 38, 20],
       [49, 43, 46],
       [36, 30, 38],
       [21, 22, 39],
       [48, 39, 41],
       [46, 20, 24]])